# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_companyprofile_lawyerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_company',
            field=models.BooleanField(default=False, verbose_name='company'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_lawyer',
            field=models.BooleanField(default=False, verbose_name='lawyer'),
        ),
    ]
