# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-12 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180209_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='Emerson Santana', max_length=255, unique=True, verbose_name='username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lawyerprofile',
            name='cpf',
            field=models.CharField(max_length=15, unique=True, verbose_name='cpf'),
        ),
    ]
