# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-12 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='emersonfidelon@gmail.com', max_length=255, unique=True, verbose_name='username'),
            preserve_default=False,
        ),
    ]
